name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: |
          echo "A secret password"
          echo "${{ secrets.PASSWORD }}"
